### ISSUE TITLE
Ground Truth of sample data

### ISSUE THREAD

**Issue by eleboss** [dylan-campbell/gosma#1]
Hi Dylan,

I have tried both of your nice works, the gopac, and gosam. 
But when using the same sample data as provided in the code file, I found that they generate two different results. 
GOPAC:
    0.9771   -0.1823    0.1099   -0.4097
   -0.0002    0.5155    0.8569    0.6900
   -0.2129   -0.8373    0.5036    3.1726

GOSMA:
   -0.4018    0.0936   -0.9109   -0.7847
    0.4731    0.8729   -0.1190    0.3235
    0.7840   -0.4788   -0.3951    2.4940
Both certificates the optimality. I cant differential them.
So could you share with me the ground truth of the sample data?

Best,
EB

**Comment by hdb1301040027** [comment]
Hi eleboss,
How to run the gopac？
I didn't modify the configuration file and ran ./gopac ./point_set.txt ./bearing_vector_set.txt ./config.txt ./output.txt . But an error occurred,
CONFIG:
(eta)->(0.0017)
(max_num_inliers)->(1)
(min_angular_resolution)->(0.001)
(min_linear_resolution)->(0.001)
(min_num_inliers)->(0)
(theta)->(0.017)
(translation_domain_expansion_factor)->(1.5)
(use_tighter_upper_bound)->(0)
(zeta)->(0.01)

-------------------0 1
Point-Set: ./point_set.txt (59 points), Bearing Vector Set: ./bearing_vector_set.txt (11 bearing vectors)

Running GOPAC (initial lower bound: 0)
Segmentation fault (core dumped) 

Have you encountered this error? Thank!

**Comment by eleboss** [comment]
Its been a year, I forget every details. But&nbsp; I remember it works, so just try to tune to code.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 25, 2021 17:29 PM
To: ***@***.***&gt;;
Cc: "Shijie ***@***.******@***.***&gt;;
Subject: Re: [dylan-campbell/gosma] Ground Truth of sample data (#1)




 
Hi eleboss,
 How to run the gopac？
 I didn't modify the configuration file and ran ./gopac ./point_set.txt ./bearing_vector_set.txt ./config.txt ./output.txt . But an error occurred,
 CONFIG:
 (eta)-&gt;(0.0017)
 (max_num_inliers)-&gt;(1)
 (min_angular_resolution)-&gt;(0.001)
 (min_linear_resolution)-&gt;(0.001)
 (min_num_inliers)-&gt;(0)
 (theta)-&gt;(0.017)
 (translation_domain_expansion_factor)-&gt;(1.5)
 (use_tighter_upper_bound)-&gt;(0)
 (zeta)-&gt;(0.01)
 
-------------------0 1
 Point-Set: ./point_set.txt (59 points), Bearing Vector Set: ./bearing_vector_set.txt (11 bearing vectors)
 
Running GOPAC (initial lower bound: 0)
 Segmentation fault (core dumped)
 
Have you encountered this error? Thank!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hdb1301040027** [comment]
> Its been a year, I forget every details. But&nbsp; I remember it works, so just try to tune to code.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Aug 25, 2021 17:29 PM To: ***@***.***&gt;; Cc: "Shijie ***@***.******@***.***&gt;; Subject: Re: [dylan-campbell/gosma] Ground Truth of sample data (#1) Hi eleboss, How to run the gopac？ I didn't modify the configuration file and ran ./gopac ./point_set.txt ./bearing_vector_set.txt ./config.txt ./output.txt . But an error occurred, CONFIG: (eta)-&gt;(0.0017) (max_num_inliers)-&gt;(1) (min_angular_resolution)-&gt;(0.001) (min_linear_resolution)-&gt;(0.001) (min_num_inliers)-&gt;(0) (theta)-&gt;(0.017) (translation_domain_expansion_factor)-&gt;(1.5) (use_tighter_upper_bound)-&gt;(0) (zeta)-&gt;(0.01)
> -------------------0 1 Point-Set: ./point_set.txt (59 points), Bearing Vector Set: ./bearing_vector_set.txt (11 bearing vectors) Running GOPAC (initial lower bound: 0) Segmentation fault (core dumped) Have you encountered this error? Thank! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thank you.
